### ISSUE TITLE
Define peer dependencies

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-node-resize#11]
jquery, oCanvas and cytoscape should be peer dependencies for this extension. However, I thik that adding new peer dependencies may require publishing version 3.0.0 (because this changes may not be backward compatible). It seems that we can add these peer dependencies when we have some other not backward compatible api changes and so we decided to publish the version 3.0.0.

**Comment by ugurdogrusoz** [comment]
@metincansiper do we still need this?

**Comment by ugurdogrusoz** [comment]
@mafar Feel free to do it now if you like

**Comment by hasanbalci** [comment]
jQuery is also added as a peer dependency in the unstable branch.
