### ISSUE TITLE
cy.json() does not export  widths and heights

### ISSUE THREAD

**Issue by mafar** [iVis-at-Bilkent/cytoscape.js-node-resize#21]
**Playground:** https://jsfiddle.net/bababalcksheep/apybnszr/16/

1. press import to start.
1. resize elements and press export to inspect json (from  ```cy.json()```)

I was expecting that after I resize few elements, and I call ```cy.json()``` I will be able to get json with modified heights and widths but this is not the case.

Is this intended ? or did I miss something ?

**Comment by kinimesi** [comment]
@mafar this is expected behaviour. "Style object is not part of the element JSON object", see https://github.com/cytoscape/cytoscape.js/issues/1218

**Comment by mafar** [comment]
https://jsfiddle.net/bababalcksheep/apybnszr/17/
I was able to do this with 

```  
window.cy.on("noderesize.resizeend", function(e, type, node) {
    node.data('width', node.width());
    node.data('height', node.height());
  });
``` 

but I dont understand the purpose of 
```
    setWidth: function(node, width) {
      node.data('width', width);
    },
    setHeight: function(node, height) {
      node.data('height', height);
    },
```
as it does not seem to do anything . Can you please explain setWidth and setHeight

**Comment by ugurdogrusoz** [comment]
@mafar please direct your Cytoscape.js related questions to the associated discussion list. Thanks!

**Comment by blazespinnaker** [comment]
Hmm, is it not possible to store the values in data() as suggested?  Lack of serialization is an issue.
