### ISSUE TITLE
Movement with arrows for simple nodes and compounds is not synchronized

### ISSUE THREAD

**Issue by leonarddrv** [iVis-at-Bilkent/cytoscape.js-node-resize#22]
When simple nodes and compounds are selected and we try to move them with arrow keys, the compounds move faster than simple nodes.

**Comment by ugurdogrusoz** [comment]
@leonarddrv can you please change the demo to include a compound node (so that I can verify)?

**Comment by leonarddrv** [comment]
You can check it on https://rawgit.com/iVis-at-Bilkent/cytoscape.js-node-resize/unstable/undoable_demo.html
