### ISSUE TITLE
Intercepting click events?

### ISSUE THREAD

**Issue by paul-bell** [iVis-at-Bilkent/cytoscape.js-node-resize#23]
Hello,

I am trying to use your very nice node-resize facility, but I've noticed one significant issue with it, at least for me.

It seems to prevent "click" events from being seen by a modal dialog I've created. Specifically, with your extension activated, the dialog can be raised but any click within the dialog's fields is not seen by the dialog object. Rather those events seem to target the underlying canvas. 

Without your extension activated, this does not happen; the dialog behaves normally.

1. why does this occur?
2. can I prevent its occurrence and continue to use the extension?

Thank you.

Cordially,

Paul

**Comment by kinimesi** [comment]
@paul-bell in [our apps](http://web.newteditor.org/) we are using the node-resize extension with modal dialog without any problem. Can you provide a minimal demo to reproduce the issue?
