### ISSUE TITLE
Document resize to content

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-node-resize#24]
We need to:
- update the README with new API on this new feature
- need to update the demo (if needed)

**Comment by ugurdogrusoz** [comment]
Can we move the node labels inside so resize node to content is more sensible?

**Comment by ugurdogrusoz** [comment]
Regarding the demo, how come Resize Node to Content (using the resize cue) increases node heights unnecessarily?
Before:
<img width="157" alt="unnessarily-resized-height-before" src="https://user-images.githubusercontent.com/3874988/43134847-131dda16-8f4c-11e8-9a8e-e43e545dc41b.png">

After:
<img width="238" alt="unnessarily-resized-height" src="https://user-images.githubusercontent.com/3874988/43134794-e9d3d872-8f4b-11e8-8467-314b68736527.png">

**Comment by ugurdogrusoz** [comment]
Who defines 50 as minimum height? Cytoscape.js or this extension?

**Comment by ahmetcandiroglu** [comment]
This extension

**Comment by ugurdogrusoz** [comment]
Let's decrease it to a reasonable value such as 25 (default./original height of the nodes in the demo)

**Comment by ugurdogrusoz** [comment]
I think we also need to make "resize node to content" consistent / compatible with the options "isFixedAspectRatioResizeMode" and "isNoResizeMode". If the latter is enabled, we shouldn't display the visual cue for resize to content at all. If the former is enabled, we should maintain the aspect ratio while resizing.

**Comment by ugurdogrusoz** [comment]
Can we also change wheel sensitivity (make it more refined, slower)?
