### ISSUE TITLE
"Cannot read property 'value' of undefined" in latest Cytoscape

### ISSUE THREAD

**Issue by incinirate** [iVis-at-Bilkent/cytoscape.js-node-resize#25]
Registering this plugin in latest cytoscape appears to work at first, with the node handles being present upon node selection, but attempting to use the handles to resize the node throws the following error:
```
core.js:5847 ERROR TypeError: Cannot read property 'value' of undefined
    at Rect.eMouseDown (cytoscape-node-resize.js:638)
```

This behavior is present in your own hosted [demo](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-node-resize/unstable/demo.html) as well.

**Comment by ugurdogrusoz** [comment]
@incinirate This should now be fixed in "unstable" branch. Please check and close this issue if you agree.

**Comment by incinirate** [comment]
Seems to be working now, thanks!
