### ISSUE TITLE
Resize visual cues not shown on Firefox

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-node-resize#26]
No problem with Chrome but with Firefox visual cues aren't shown. See [this issue](https://github.com/iVis-at-Bilkent/pathway-mapper/issues/195).

**Comment by Rgtemze** [comment]
I did not put resizeToContentCueImage field into my node resize options but it did not provide a default resizeCue. Hence, I needed to make the same change (adding width and height property to svg) to my own resizeCue.svg and include that one in the nodeResize options.

**Comment by hasanbalci** [comment]
@Rgtemze The default value for resizeToContentCueImage option is `'/node_modules/cytoscape-node-resize/resizeCue.svg'`. If it didn't provide the default image, probably your path to the default image file is different than the above, so you should set it accordingly. However, the solution you mentioned above can also be used as an alternative solution.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Does that mean to use the default image, we still need to provide a path (to the default image)?  Poor design choice?

**Comment by hasanbalci** [comment]
@ugurdogrusoz If we don't provide a path, it will use the default path value which is `'/node_modules/cytoscape-node-resize/resizeCue.svg'`and this will work if the node_modules folder and the file where the node-resize options are set in the same level of the folder structure. If they are not in the same level, then one need to give the correct path to the default cue image.

**Comment by ugurdogrusoz** [comment]
@Rgtemze Could you please try changing the path so that default image is properly used?

**Comment by ugurdogrusoz** [comment]
@Rgtemze confirms that suggested change works.
