### ISSUE TITLE
Demos of the unstable branch don't resize

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape.js-node-resize#27]
Demos of the unstable branch don't resize. Konva is giving out some errors.

![image](https://user-images.githubusercontent.com/38570154/64178704-a44ee580-ce6a-11e9-9ab7-867418cda6e5.png)

**Comment by hasanbalci** [comment]
Currently and interestingly, master branch points to demo files of unstable branch and unstable branch points to demo files of master branch. Unstable demo files are working good, just need link update.

**Comment by nasimsaleh** [comment]
demo files links are changed now, you can test again.

**Comment by ugurdogrusoz** [comment]
@PermanAtayev pls confirm and close if ok

**Comment by PermanAtayev** [comment]
It works!
