### ISSUE TITLE
Cytoscape dependency

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape.js-node-resize#28]
In the documentation it writes that the cytoscape's version is 2.7.0 or higher, while in the package.json the dependency is 3.0.0 or higher

**Comment by ugurdogrusoz** [comment]
Let's make sure we use the latest Cytoscape.js. Let's also update the documentation to state this.

**Comment by nasimsaleh** [comment]
cytoscape dependency is verysion 3.2.0 and higher now. Updated in readme file and package.json

**Comment by ugurdogrusoz** [comment]
@PermanAtayev pls confirm and close if ok

**Comment by PermanAtayev** [comment]
Seem's to be good.
