### ISSUE TITLE
Ineffective extension options

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-node-resize#29]
`boundingRectangle` and `zIndex` options are not effective (They aren't used in the extension code). They can be removed from options totally or their functionality can be implemented.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh please take a look and let's discuss how to proceed.

**Comment by nasimsaleh** [comment]
Bounding rectangle option is removed. zIndex option is usable now.

**Comment by ugurdogrusoz** [comment]
@hasanbalci pls confirm and close if OK
