### ISSUE TITLE
Change size of compound node

### ISSUE THREAD

**Issue by zeeshan-maavan** [iVis-at-Bilkent/cytoscape.js-node-resize#32]
I want to change the size of  compound node but could not find any solution there.

**Comment by hasanbalci** [comment]
Resize of compound nodes is disabled by default in the following option: 
`isNoResizeMode: function (node) { return node.is(".noResizeMode, :parent") } `. 
You can enable it by just setting the option as 
`isNoResizeMode: function (node) { return node.is(".noResizeMode") }`
