### ISSUE TITLE
visually overlapping with edgehandles

### ISSUE THREAD

**Issue by Hoogkamer** [iVis-at-Bilkent/cytoscape.js-node-resize#44]
Hi, thanks for this nice work!
First a little ' bug': you forgot a comma in the documentation of the Default Options for the 'cursors' property (this page: https://github.com/iVis-at-Bilkent/cytoscape.js-node-editing)

And my question, how do I avoid overlaps between the editing handles and the edge drawing handle. I would like to have the latest one on top (or remove the middle top editing handle)
![image](https://user-images.githubusercontent.com/17671871/179346343-a49085ad-1580-407e-8548-7627de137d52.png)

**Comment by hasanbalci** [comment]
Hi @Hoogkamer, I think you can have the drawing handle on top by increasing its z-index value. We don't have an option to remove the middle top handle, but you can disable it by using `isFixedAspectRatioResizeMode` option which allows to edit node size only from corners of the node.

**Comment by hasanbalci** [comment]
@Hoogkamer Thanks for the PR, can you please open it to the unstable branch as the development is done first in the unstable branch and then we merge it to the master before the release?
