### ISSUE TITLE
cytoscape not defined

### ISSUE THREAD

**Issue by blacksmithblack** [iVis-at-Bilkent/cytoscape.js-node-resize#5]
Hi,

Looks like there is a similar error with this extension, as there was with https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/issues/5

When I require cytoscape-node-resize, I get the following error..

cytoscape-node-resize.js:681Uncaught ReferenceError: cytoscape is not defined
(anonymous function) @ cytoscape-node-resize.js:681
2976 @ cytoscape-node-resize.js:684
**webpack_require** @ bootstrap 7cf81ac…:50
2383 @ app.js:12
**webpack_require** @ bootstrap 7cf81ac…:50
0 @ analysisCentre.entry.js:29
**webpack_require** @ bootstrap 7cf81ac…:50
webpackJsonpCallback @ bootstrap 7cf81ac…:21
(anonymous function) @ analysisCentre.bundle.js?v=8467:1

**Comment by metincansiper** [comment]
Hi @blacksmithblack,
Sorry for my late response when I tried to use this extension by requiring it I get an error as well but this error is not similar to the one you specified. 

Here is the screenshot of my error.

![capture](https://cloud.githubusercontent.com/assets/6534865/19683400/b91318ce-9aba-11e6-9721-0fedcd75441e.PNG)

I think that this error is related to 'ocanvas' library and I filed this issue on their repository ('https://github.com/koggdal/ocanvas/issues/130')

Do you still get the same error in this issue or you have a problem similar to the one I have.

**Comment by metincansiper** [comment]
The response from 'https://github.com/koggdal/ocanvas/issues/130' is that 'Unfortunately oCanvas is only supported in browser environments so far.' That is to enable users to 'require' this extension we need to get rid of 'ocanvas' dependency.

**Comment by metincansiper** [comment]
@blacksmithblack as we discussed previously oCanvas is only supported in browser environments so far.  Therefore, now we do not force commonjs users to pass an 'oCanvas' instance by a parameter. We expect them to include oCanvas in their html file. There is a similar usage here (https://github.com/cytoscape/cytoscape.js-qtip) as well ('qTip' which is not supported by commonjs is a dependency of that extension).

If there is no problem for you we can close the issue.
