### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-node-resize#6]
Selection seems to be extremely slow with the introduction of this extension in ChiSE (e.g. try Select All Nodes of This Type for macromolecules of the default sample pathway).

**Comment by mrsfy** [comment]
This bug is also seems fixed by 123cc747e0bba5b097adc3e934acd1416172f646. I just published new version of this extension to npmjs.

**Comment by ugurdogrusoz** [comment]
Looks like there are still issues with performance. For example, see this: https://github.com/iVis-at-Bilkent/chise.js/issues/65.

**Comment by ugurdogrusoz** [comment]
Another problem is if you select a node and then drag it (especially a compound node with much content), the performance degrades drastically.

**Comment by metincansiper** [comment]
@ugurdogrusoz some performance improvements are done on this extension since this issue is opened. Please would you evaluate the performance again?
