### ISSUE TITLE
Filter nodes to which resizing grapples should appear

### ISSUE THREAD

**Issue by mafar** [iVis-at-Bilkent/cytoscape.js-node-resize#9]
Hi,
I want to hide grapples for some nodes. is it possible ?
I know there is ```isNoResizeMode``` option but it disables resizing. 
I want some nodes based on ```data()```` that when clicked , there should be no grapples visible.
Is it possible via cytoscape style?

**Comment by djangosdk** [comment]
I added https://github.com/djangosdk/cytoscape.js-node-resize/commit/f9023f4ad85a8dd5752bcb843f65225ddf7aab08. It works for me.

**Comment by djangosdk** [comment]
Opps an extra bracket after true in 
``` isResizable: function (node) { return true**)** },  ```

**Comment by ssayan** [comment]
This is useful, but I wonder if a better approach would be a list of node types to filter in cyto init?

**Comment by djangosdk** [comment]
in my case, I need to decide based on some nested key in node data that if it should be grapable.
Gives more power this way to filtering.

**Comment by mafar** [comment]
any update ?
can you please merge it ?
having it as a function gives more power as one can check for classes , check for data values and has to return true or flase

**Comment by ugurdogrusoz** [comment]
What do you think @kinimesi ?

**Comment by mafar** [comment]
@kinimesi  @ugurdogrusoz
Please review. I tested it and it works

https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize/pull/20
